<?php
require_once(ROOT_LIBS."/phpexcel/PHPExcel.class.php");
require_once(ROOT_LIBS."/phpexcel/PHPExcel/Writer/Excel2007.php");
ini_set("max_execution_time", 2400); // s 40 分钟 
//修改此次的最大运行内存 
ini_set("memory_limit", 1048576000); // Byte 1000 兆，即 1G
class phpexcel_main extends STpl{
      public  function __construct(){
        $user = user_api::loginedUser();
        if (empty($user)) {
            $this->redirect("/site.main.login");
        }   
        $org=user_organization::subdomain();
        $this->orgOwner = !empty($org) ? $org->userId : 0;
    } 
	public function pageEntry($inPath){
        $params = array(
            'condition' => "fk_user_owner={$this->orgOwner} AND status=1 ",
            'page'      => !empty($_REQUEST['page']) && (int)($_REQUEST['page']) ? (int)($_REQUEST['page']) : 1,
            'length'    => 10000, 
            'item'      => array('fk_user', 'count(*) as courseNum'),
            'groupBy'   => array('fk_user'),
            'orgOwner'  => $this->orgOwner
        );  
        $list = course_api::getOrgStudentList($params);
        if(empty($list->data->list)){
           echo '<script type="text/javascript">alert("没有学生")</script>';
           exit;
        }
        $data=array();
        foreach ($list->data->list as $v) {
            $data[] = array(
                'id' => !empty($v->fk_user) ? $v->fk_user : '',
                'name' => !empty($v->real_name) && trim($v->real_name) ? $v->real_name : (!empty($v->name) ? $v->name : ''),
                'gender' => !empty($v->gender) ? ($v->gender==1 ? '男' : '女') : '',
                'age' => !empty($v->birthday) ? utility_tool::getAge($v->birthday) : '',
                'school' => !empty($v->school_name) ? $v->school_name : '',
                'mobile' => !empty($v->mobile) ? $v->mobile : '',
                'courseNum' => !empty($v->courseNum) ? $v->courseNum : 0,
                'thumb' => !empty($v->thumb_small) ? $v->thumb_small : ''
            );
        }
        //实例化表格
        $objPHPExcel = new PHPExcel(); 
        //保存excel—2007格式
        $objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
        //基本设置
        $fileName="学生列表";
        $objProps = $objPHPExcel->getProperties();
        $objProps->setCreator("www.yunke.com");
        $objProps->setLastModifiedBy("www.yunke.com");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, yunke");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("报表");
        $objPHPExcel->setActiveSheetIndex(0);
        // 行高
        for ($i = 1; $i <=10; $i++) {
            $objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(22);
        }
        $objActiveSheet = $objPHPExcel->getActiveSheet();
        $objActiveSheet->setTitle($fileName);

        //设置表头
        $objActiveSheet->getStyle('A1')->getFont()->setBold(true);
        $objActiveSheet->getStyle('B1')->getFont()->setBold(true);
        $objActiveSheet->getStyle('C1')->getFont()->setBold(true);
        $objActiveSheet->getStyle('D1')->getFont()->setBold(true);
        $objActiveSheet->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objActiveSheet->getStyle('B1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objActiveSheet->getStyle('C1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objActiveSheet->getStyle('D1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objActiveSheet->setCellValue('A1', 'ID');
        $objActiveSheet->setCellValue('B1', '姓名');
        $objActiveSheet->setCellValue('C1', '性别');
        $objActiveSheet->setCellValue('D1', '年龄');
    
        //设置第二列为文本格式 防止科学计数
        $objActiveSheet->getStyle('B1')->getNumberFormat()->setFormatCode(\PHPExcel_Style_NumberFormat::FORMAT_TEXT);
        //填充表格内容
        $j=2;
        foreach($data as $k=>$v){
            $objActiveSheet->setCellValue('A' . $j, $v['id']);
            $objActiveSheet->setCellValue('B' . $j, ' '.$v['name']);
            $objActiveSheet->setCellValue('C' . $j, $v['gender']);
            $objActiveSheet->setCellValue('D' . $j, $v['age']);
            $objActiveSheet->getStyle('A' . $j)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            $objActiveSheet->getStyle('B' . $j)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
            $objActiveSheet->getStyle('C' . $j)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            $objActiveSheet->getStyle('D' . $j)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            $j++;
        }
        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        if(empty($fileName)){
            $ftime = time();
            $outputFileName = $ftime . ".xls";
        }else{
            $outputFileName = $fileName . ".xls";
        }
        //加此防乱码
        ob_clean();
        @header("Pragma: public");
        @header("Expires: 0");
        @header("Cache-Control:must-revalidate,post-check=0,pre-check=0");
        @header("Content-Type:charset=UTF-8");
        @header("Content-Type:application/force-download");
        @header("Content-Type:application/vnd.ms-execl");
        @header("Content-Type:application/octet-stream");
        @header("Content-Type:application/download");
        @header('Content-Disposition:attachment;filename="' . $outputFileName . '"');
        @header("Content-Transfer-Encoding:binary");
        $objWriter->save('php://output');
    }
}


